### ISSUE TITLE
cortina.yaml

### ISSUE THREAD

**Issue by rootshell1989** [icarome/esphome#1]
Hi
thanks for the great efforts 

i tried to use corina.yaml by copying the file into my hassio esphome  folder and then validate the file but im getting this error 

cover.template: [source /config/esphome/cortina.yaml:54]

 [position_action] is an invalid option for [cover.template]. Did you mean [stop_action], [tilt_action], [open_action]?
  position_action:

**Comment by icarome** [comment]
Try using the ESPHome Dev version

**Comment by rootshell1989** [comment]
for some reason i could not install ESPHome Dev version
it gives me an error Failed to install addon, Unknown Error, see logs

**Comment by rootshell1989** [comment]
i installed a 64 version of hassio then install esphome dev and that solved the proplem 
thanks for help
